[tool.poetry]
name = "twc-cli"
version = "2.3.0"
description = "Timeweb Cloud Command Line Interface."
authors = ["ge <dev@timeweb.cloud>"]
homepage = "https://github.com/timeweb-cloud/twc"
repository = "https://github.com/timeweb-cloud/twc"
license="MIT"
readme = "README.md"
include = ["CHANGELOG.md", "COPYING"]
packages = [{ include = "twc", from = "." }]

[tool.poetry.dependencies]
python = "^3.7.9"
requests = "^2.31.0"
typer = "^0.7.0"
shellingham = "^1.5.0.post1"
colorama = "^0.4.6"
toml = "^0.10.2"
pyyaml = "^6.0"
pygments = "^2.15.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pylint = "^2.17.2"

[tool.poetry.scripts]
twc = "twc.__main__:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "too-few-public-methods",
    "too-many-public-methods",
    "too-many-instance-attributes",
    "too-many-branches",
    "too-many-statements",
    "too-many-arguments",
    "too-many-locals",
    "too-many-lines",
    "unused-argument",  # unused 'verbose' arg is OK
    "duplicate-code",
    "invalid-name",
    "missing-function-docstring",
]
